install:
  bun install

dev:
  bun --watch src/index.ts

build:
  bun build src/index.ts --outdir ./build --target node

run:
  node build/index.js

clean:
  rm -rf ./dist ./node_modules

gen-env-template:
  grep -v '^#' .env | sed 's/=.*/=/' | awk NF > .env.template