name: ci

on:
  push:
    tags:
      - v*
    branches:
      - github-actions

env:
  VERSION: "latest"

jobs:
  docker:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Set short git commit SHA
        id: vars
        run: |
          calculatedSha=$(echo ${{ github.sha }} | cut -c1-8)
          TIMEVER=$(date -u "+%Y-%m-%d-%H%M")
          echo "VERSION=$TIMEVER-$calculatedSha" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          build-args: |
            VERSION=${{ env.VERSION }}
          tags: ghcr.io/${{ github.repository }}/app:latest, ghcr.io/${{ github.repository }}/app:${{ env.VERSION }}
